import type { Metadata } from 'next'
import { cn } from '@/utilities/cn'
import { serif, sansSerif } from './fonts'
import { TopNavi } from '@/components/TopNavi'

import './app.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type RootLayoutProps = {
  children: React.ReactNode
}
export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={cn(serif.variable, sansSerif.variable, 'max-w-screen-lg container mx-auto')} suppressHydrationWarning>
        <TopNavi />
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
